#pragma once


// 201 부터 시작한다.
enum class ERROR_CODE : short
{
	NONE = 0,
	UNKNOWN = 1,

	// 로그인 관련
	LOGIN_FAIL = 11,
	LOGIN_ALREADY = 12,


	// 회원가입 관련
	REGISTER_DUPLICATE_ID = 21,
	REGISTER_DUPLICATE_NICKNAME = 22,
	REGISTER_INVALID_ID = 23,
	REGISTER_INVALID_PW = 24,
	REGISTER_INVALID_NICKNAME = 25,



	DB_ERROR = 30,

	MATCH_FAIL_SERVER_FULL = 41,
	MATCH_FAIL_ALREADY_IN_ROOM = 42,
	MATCH_FAIL_INVALID_REQUEST = 43,

	UNASSIGNED_ERROR = 201,

	MAIN_INIT_NETWORK_INIT_FAIL = 206,

	USER_MGR_ID_DUPLICATION = 211,
	USER_MGR_MAX_USER_COUNT = 212,
	USER_MGR_INVALID_SESSION_INDEX = 213,
	USER_MGR_NOT_CONFIRM_USER = 214,
	USER_MGR_REMOVE_INVALID_SESSION = 221,
	USER_MGR_INVALID_USER_INDEX = 222,

};
